<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf8">
        <link rel="stylesheet" href="/css/bootstrap.min.css" type="text/css">
        <link rel="stylesheet" href="/css/bootstrap-responsive.min.css" type="text/css">
        <title>
            <?=$this->title;?>
        </title>
    </head>
    <body>
        <div class="container">
            <?= $this->layout()->content; ?>
        </div>
    </body>
</html>