<!DOCTYPE html>
<?php
if (!isset($this->cart))
    $cart = array();
?>
<html lang="ru">
    <head>
        <meta charset="utf8">
        <link rel="stylesheet" href="/css/bootstrap.min.css" type="text/css">
        <link rel="stylesheet" href="/css/bootstrap-responsive.min.css" type="text/css">
        <link rel="stylesheet" href="/css/style.css" type="text/css">
        <script src="/js/jquery-1.9.1.min.js"></script>
        <script src="/js/bootstrap.js"></script>
        <script src="/js/cart.js"></script>
        <title>
            <?= $this->title; ?>
        </title>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <i class="icon-reorder icon-2x"></i>
                    </a>
                    <span class="brand">IT-shop</span>
                    <ul class="nav nav-collapse pull-left">
                        <li class="divider-vertical"></li>
                        <li><a href="#"><i class="icon-home"></i>Главная</a></li>
                        <li><a href="/catalog">Каталог</a></li>
                    </ul>
                    <ul class="nav nav-collapse pull-right">
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Товары<i class="caret"></i></a>
                            <ul class="dropdown-menu cart">
                                <li><a href="/cart/list">Оформить</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container">
            <?= $this->layout()->content; ?>
        </div>
    </body>
</html>