<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf8">
        <link rel="stylesheet" href="/css/bootstrap.min.css" type="text/css">
        <link rel="stylesheet" href="/css/bootstrap-responsive.min.css" type="text/css">
        <title>
            <?=$this->title;?>
        </title>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="span3"></div>
                <div class="span9">
                    <?= $this->layout()->content; ?>
                </div>
            </div>
        </div>
    </body>
</html>