<div class="row">
    <div class="span3">
        <div class="well well-small affix">
            <ul class="nav nav-list">
                <li><a href="/admin/add-category">Добавить категорию</a></li>
                <li class="active"><a href="/admin/add-item">Добавить товар</a></li>
            </ul>
        </div>
    </div>
    <div class="span9">
        <form method="POST">
            <table>
                <tbody>
                    <tr>
                        <td>
                            Название Товара
                        </td>
                        <td>
                            <input name="name">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Категория
                        </td>
                        <td>
                            <select name="category_id">
                                <option selected disabled value="0">Выберете категорию</option>
                                <option value="0">Корневой</option>
                                <?php foreach ($this->parent_category as $row): ?>
                                    <option value="<?= $row->categoryId; ?>"><?= $row->name; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Цена
                        </td>
                        <td>
                            <input type="number" min="0" step="0.01" name="price">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input class="btn btn-primary" type="submit" value="Save" name="btSave">
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
        <ul>
            <?php foreach ($this->list_items as $row): ?>
                <li><?= $row->name; ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
