<form method="POST">
    <table>
        <tbody>
            <tr>
                <td>
                    Название Товара
                </td>
                <td>
                    <input name="name">
                </td>
            </tr>
            <tr>
                <td>
                    Категория
                </td>
                <td>
                    <select name="parent">
                        <option selected disabled value="0">Выберете категорию</option>
                        <option value="0">Корневой</option>
                        <?php foreach ($this->parent_category as $row): ?>
                        <option value="<?=$row->categoryId;?>"><?=$row->name;?></option>
                        <?php endforeach;?>
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    <input class="btn btn-primary" type="submit" value="Save" name="btSave">
                </td>
            </tr>
        </tbody>
    </table>
</form>